name:                servant-client-haxl
version:             0.0.0.0
synopsis:            Haxl-based client functions for servant APIs
description:
homepage:            http://github.com/jkarni/servant-client-haxl#readme
license:             BSD3
license-file:        LICENSE
author:              Julian K. Arni
maintainer:          jkarni@turingjump.com
copyright:           (c) 2017 Julian K. Arni
github:              jkarni/servant-client-haxl
stability:           alpha
tested-with:         GHC == 7.10.3, GHC == 8.0.2

ghc-options: -Wall

dependencies:
  - base >= 4.8 && < 4.10
  - bytestring >= 0.10 && < 0.11
  - text >= 1 && < 2
  - servant-client >= 0.12 && < 0.13
  - haxl >= 0.5 && < 0.6
  - http-client >= 0.5 && < 0.6
  - http-types >= 0.9 && < 0.10
  - hashable >= 1 && < 2

default-extensions:
  - AutoDeriveTypeable
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - KindSignatures
  - MultiParamTypeClasses
  - OverloadedStrings
  - RankNTypes
  - ScopedTypeVariables
  - TypeFamilies
  - TypeOperators

library:
  source-dirs:      src
  other-modules:    []

tests:
  spec:
    main:            Main.hs
    source-dirs:     test
    dependencies:
      - servant-client-haxl
      - hspec > 2 && < 3
      - QuickCheck >= 2.8 && < 2.10
      - quickcheck-instances >= 0.3 && < 0.4
