flags: {}
extra-package-dbs: []
packages:
- '.'
- location: '../servant/servant'
  extra-dep: true
- location: '../servant/servant-client'
  extra-dep: true
- location: '../servant/servant-client-core'
  extra-dep: true
extra-deps: []
resolver: lts-9.3
